### ISSUE TITLE
How do i do?

### ISSUE THREAD

**Issue by naufdotal** [bluescreencs/RF-Online-macros#1]
Hello, i found this on github today, and i'm a RF online player.
How do i do, to use this program? i never use .ahk

**Comment by bluescreencs** [comment]
oh man... my bad, too busy irl , i did not even noticed. Anyway, just in case you are still checking this out, i'll try my best to recall, these macros/clickers were (badly) written specifically for an old server we used to play with. Probably the easiest to explain are the [RFO_AFK_Tools.ahk](https://github.com/LanLayug/RF-Online-macros/blob/master/RFO_AFK_Tools.ahk) which allow you to spam "x" for looting and allows an accretian striker to launch its 2 skills (doom blast? chain rocket? can't remember) if their set in "F1" and "F2" while afk (think pitboss farming) and the [Mysterious_Box_Clicker.ahk](https://github.com/LanLayug/RF-Online-macros/blob/master/Mysterious_Box_Clicker.ahk) that just spams "F10" we used this to open leon boxes or any stackable items that need to be right clicked.

While the [iggy_Xchanger.ahk](https://github.com/LanLayug/RF-Online-macros/blob/master/iggy_Xchanger.ahk) and [upgrader_Clicker.ahk](https://github.com/LanLayug/RF-Online-macros/blob/master/upgrader_Clicker.ahk) are macros that deals with item combination on Hero (Lotan? Lotar?)  that allows Hero combination of iggy and favor talics in exchange for weapon/armor upgrader, so I think this is server specific and also drag the Hero Combination hud to the top left corner in order for this clicker to work properly.

I think you need to install autohotkey in order to launch ahk files or convert them to exe to distribute elsewhere.

Anyway, this is a long shot and I hope it helps.

**Comment by bluescreencs** [comment]
awfully explained, still explained.
